### ISSUE TITLE
jenkins has no space

### ISSUE THREAD

**Issue by diatomsRcool** [bio-guoda/guoda-services#63] opened 2019-01-04 21:49 UTC
I'm getting the
java.io.IOException: No space left of device
error. I think the last time a bunch of logs had to be deleted.

**Comment by mjcollin** [comment] 2019-01-04 22:07
ACK. I noticed that I think Wednesday. It's technically out of inodes, not disk space. I think it's because @jhpoelen wrote out a preston archive to disk and that's a huge number of often small files which use up all the inodes.

@jhpoelen the preston.acis.ufl.edu host is backed by a ZFS volume over NFS and ZFS doesn't use inodes so this isn't an issue there.

I'll try to figure out a better pattern this weekend.

**Comment by jhpoelen** [comment] 2019-01-15 13:37
I've deleted  a jenkins job "preston-dataone". This job created a large volume of files and caused the inode quota to deplete. I've confirmed that jenkin jobs are now able to create files again. Closing issue. Related issue https://github.com/bio-guoda/preston/issues/9 .

**Closed as completed by jhpoelen** 2019-01-15 13:37 UTC
