### ISSUE TITLE
Effechecka API down due to rebooted node and no resources

### ISSUE THREAD

**Issue by mjcollin** [bio-guoda/guoda-services#53] opened 2018-07-24 18:51 UTC
One of the nodes that the Effechecka API was deployed on was rebooted yesterday. Marathon still has a reference to the instance that was on that machine and the monitoring system was occasionally seeing it. (Not sure why, HAProxy had marked it down.) Restarted Marathon to attempt to get rid of it but in the mean time an occurrence checklist job was submitted which is using all resources so Marathon can't deploy the app again.

**Comment by jhammock** [comment] 2018-07-24 18:55
Sorry to hold things up- I am Updating Monitors, which usually takes ~21 hours. Kill it if you need to; otherwise it should be done by morning.

**Comment by mjcollin** [comment] 2018-07-25 14:36
Apparently I should just be more patient. Restarting Marathon seems to have allowed the stuck instance to get cleaned up but only after scaling to 0 and back. Scaling back up was not working because it couldn't get resources due to a running checklist job. Now that that job is done, scaling down and back up to 3 works fine. API back up.

@jhammock I did kill your update monitors Jenkins job but that wasn't the issue. Please restart whenever you like.

**Comment by mjcollin** [comment] 2018-07-26 14:47
Reopening due to API being not quite the same as before. The /occurrences endpoint as used on the front page of http://gimmefreshdata.github.io returns status: "ready" and items: [ ] so nothing is displayed. However, the same default query to the /checklist endpoint returns many items.

Monitoring for this service is inconsistent, Marathon checks /checklist and Zabbix checks /occurrences. When the difference between the two is resolved, reevaluate what the correct thing to monitor is where (likely both endpoints since it's possible for them to be different.)

@jhpoelen do you have a pointer on what the difference between these endpoints is designed to be?

Full working and non-working URLs:
```
http://api.effechecka.org/occurrences?limit=20&taxonSelector=Aves%2CInsecta&wktString=POLYGON%20((-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786))


http://api.effechecka.org/checklist?taxonSelector=Aves%2CInsecta&wktString=POLYGON%20((-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786))&limit=20
```

**Comment by jhammock** [comment] 2018-07-30 17:02
this may be naive, but I am running update monitors again in the hope that the latest symptoms are a result of the interrupted job.

**Comment by jhammock** [comment] 2018-07-31 15:08
Alas. Monitors are updated. Checklist still working, occurrences still empty.

**Comment by diatomsRcool** [comment] 2018-08-01 19:49
I am also have problems.....

**Comment by jhpoelen** [comment] 2018-08-09 20:34
@mjcollin using the api endpoints occurrences/ checklist as health checks exercise the full stack of both effechecka's checklist generator and freshdata. For both results, non-zero items are expected. This assertion is valid for the checklist, but not for the occurrences endpoint. However, results are returned, so the API is working as expected, but for some (unknown) reason, the freshdata queries are not being populated. So, as far as health checks go: use http://api.effechecka.org/ping to check whether the api is available, and use queries below (as before) to assert some basic assumptions related to expected results.  

```
http://api.effechecka.org/occurrences?limit=20&taxonSelector=Aves%2CInsecta&wktString=POLYGON%20((-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786))

http://api.effechecka.org/checklist?taxonSelector=Aves%2CInsecta&wktString=POLYGON%20((-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786))&limit=20
```

**Comment by jhpoelen** [comment] 2018-08-09 20:45
So, as far as I am concerned, the API is up and running. This is why I am closing the issue. Suggest to open another, more specific issue on a specific query that is returning unexpected results. As you probably now, the narrower (or more specific) the issue description, the easier it is to determine the root cause.

**Closed as completed by jhpoelen** 2018-08-09 20:45 UTC

**Comment by mjcollin** [comment] 2018-08-09 21:23
I updated the Zabbix monitoring to check both end points so we won't have mis-matching monitoring by different systems. The proxy will use the ping end point to make sure the service is running. Zabbix will use full API calls to make sure the service is returning expected results.
